### PR TITLE
Alert, when user is about to open more than 8 saved sites

### PR DESCRIPTION
**Pull request by tomasko126**
@studiotbt Could you please test? Thanks :)

### CODE REVIEW

**Comment by studiotbt** [comment]
the function Open all Notes, isnt responding for me. :/ Nothing happens when I click.

**Comment by studiotbt** [comment]
the code looks like some advanced restructuring :-)

**Comment by tomasko126** [comment]
@studiotbt Hah, I had to move some code to the background file to make alert working :) Do you see any error in the console?

**Comment by studiotbt** [comment]
@tomasko126  Uncaught TypeError: BG.openAllSites is not a function  / is all i get

**Comment by tomasko126** [comment]
@studiotbt What browser are you using? If Chrome, go to chrome://chrome and paste here version number of Chrome you are testing Notemark on.

**Comment by studiotbt** [comment]
@tomasko126 it was Version 46.0.2490.80 (64-bit), now it says i need to restart chrome for update. going to do that now

**Comment by studiotbt** [comment]
@tomasko126 guess it works!
screen shot 2015-11-26 at 23 14 50

**Comment by studiotbt** [comment]
Will need to shorten that bloody title :)

**Comment by tomasko126** [comment]
@studiotbt Do whatever you want! :)

**Comment by studiotbt** [comment]
this release have to wait a little, till chrome new version has spread more.

**Pull request merged**
