### PR TITLE
Fixed saving of all tabs

### PR DESCRIPTION
**Pull request by tomasko126**
@studiotbt Could you test & review? :)

### CODE REVIEW

**Comment by studiotbt** [comment]
it still doesn't add all tabs and, it seems to me is that it doesn't add sites that are 'secure' (i.e https)
sorry for late reply, not feeling well these days.

**Comment by tomasko126** [comment]
@studiotbt Confirmed, thanks for repro steps :) Could you retest again?

**Comment by studiotbt** [comment]
it works, it now adds for example (https) twitter.com too. but it still doesnt add all my tabs.

it appear it adds only 3 tabs (usually from right to left), i have 8 tabs. maybe there is a limit, which requires somesort of delay after each added note, but i think the bottom line is it doesnt cycle through all the tabs. Havent figured out the cause, does it work for u?

note: This may be off subject, but the heart also remained filled when removed from the list.

**Comment by tomasko126** [comment]
@studiotbt Strange :/ It doesn't work for me either. Will try to fix it somehow. Thanks for quick feedback!

**Comment by tomasko126** [comment]
@studiotbt I've figured out the problem of this issue. This issue is occurring, because I've changed the permission of the extension in `manifest.json` file. In order to properly enable permissions for our extension, it must be re-installed. After installation, it works correctly.

**Comment by studiotbt** [comment]
awesome, you're right. just opened it with a new person (user) in chrome, and works!
the heart issue i mentioned above still remains. but its a minor issue because u already had the solution :-)

**Comment by tomasko126** [comment]
@studiotbt Alright, will merge this then :) (Meanwhile, I've fixed the icon)

**Pull request merged**
