### PR TITLE
Open notes in current window

### PR DESCRIPTION
**Pull request by tomasko126**
Current result:
Each saved note is opened in a new window.

Expected result:
Open saved notes in current window by default.

### CODE REVIEW

**Comment by studiotbt** [comment]
fantastical! it works. please merge and package, and i will put it up tomorrow morning!

**Comment by tomasko126** [comment]
@studiotbt Finally it's working properly :) I am gonna make a new release!

**Comment by tomasko126** [comment]
@studiotbt I've released 1.0.1 version - please take a look [here](https://github.com/tomasko126/notemark/releases/tag/1.0.1)

**Comment by studiotbt** [comment]
tested and happy! will let u know when its live!

**Pull request merged**
